Task/oauth
watchdogpolska/small_eod pull request #908
Opened 2021-04-20 03:10 UTC by MichalKarol

Implementacja OAuth2 dla EOD

2021-04-20 09:20 UTC, fervero commented on frontend-project/src/components/FetchLink.tsx
> +        setFetching(false);
Gaszenie spinnera albo w bloku `finally` (lepiej), albo musi się powtarzać i w `then`, i w `catch`.

2021-04-20 09:20 UTC, fervero commented on frontend-project/src/components/FetchSelect.tsx
> +  function extractOptionsFromApiResults(results: T[]) {
Lepiej jako arrow function

2021-04-20 09:20 UTC, fervero commented on frontend-project/src/components/Table/index.tsx
> +            Object.entries(filters).reduce(
Zrób z tego jakąś nazwaną funkcję `(filters) =>`, bo się zrobił coś z 6-ty poziom wcięć.

2021-04-20 09:20 UTC, fervero commented on frontend-project/src/components/Table/index.tsx
> +function SearchContainer(props: { value: string; onSearch: (value: string) => void }) {
Może do osobnego pliku?

2021-04-20 09:20 UTC, fervero commented on frontend-project/src/hooks/useAuth.ts
> +        .catch(() => logout());
Chyba wystarczy
```
.then(setTokens)
.catch(logout)
```

2021-04-20 09:20 UTC, fervero commented on frontend-project/src/hooks/useAuth.ts
> +    return isLoggedIn() ? Number(localStorage.getItem(EXPIRES)) : 10000;
Zrób z 10000 jakąś stałą w scopie useAuth(), obok `ACCESS_TOKEN` itd.

2021-04-20 09:20 UTC, fervero commented on frontend-project/src/hooks/useDebounce.ts
> +  function debounce(baseFunc: () => void) {
Może zaimportuj `debounce` lodasha?

2021-04-20 09:20 UTC, fervero commented on frontend-project/src/components/FileCard/FileCard.tsx
> +          onClick={() => {
Zrób z tego jakąś funkcję zdefiniowaną na zewnątrz szablonu

2021-04-20 09:20 UTC, fervero commented on frontend-project/src/layouts/LoginLayout.tsx
> +              System elektronicznego obiegu dokumentów fundacji Watchdog Polska
Zdaje się, oficjalnie Sieć Obywatelska Watchdog Polska

2021-04-20 09:20 UTC, fervero commented on frontend-project/src/pages/features/FeaturesDetailView.tsx
> +      FeaturesService.fetchOne(Number(match.params.id)).then(response => setEditedItem(response));
```
{
}
```

2021-04-20 11:29 UTC, MichalKarol commented on frontend-project/src/components/Table/index.tsx
> +function SearchContainer(props: { value: string; onSearch: (value: string) => void }) {
Wykorzystywany tylko w jednym specyficznym miejscu więc nie ma sensu wypinać do osobnego pliku.

2021-04-20 11:44 UTC, MichalKarol commented on frontend-project/src/hooks/useDebounce.ts
> +  function debounce(baseFunc: () => void) {
Chciałbym nie dodawać nowych zależności do lodasha (szczególnie że nie mamy za dużo). Debounce w sumie jest bardziej na przyszłość, bo głównie chodzi o debouncePromise, ale w sumie debounce był za darmo przy okazji.

2021-04-20 11:46 UTC, MichalKarol commented on frontend-project/src/components/FetchSelect.tsx
> +  function extractOptionsFromApiResults(results: T[]) {
Nie widzę zysku z wykorzystania arrow function, szczególnie że utraci semantyka jako że `const extractOptionsFromApiResults = () => ...` będzie słabiej wskazywało na funkcję, niż explicit `function extractOptionsFromApiResults() { ...`

2021-04-21 22:14 UTC, ad-m commented on backend-project/small_eod/users/providers.py
> +            redirect_uri=request.build_absolute_uri("/login/callback"),
Czy możemy w tym miejscu jednak wykorzystać rozwiązywanie URLI od Django? `reverse` w mojej ocenie warto używać.

2021-04-21 22:18 UTC, ad-m commented on frontend-project/src/layouts/LoginLayout.tsx
> +              System elektronicznego obiegu dokumentów fundacji Watchdog Polska
Poza tym jesteśmy stowarzyszeniem, a nie fundacją (mamy członków i odrobinę więcej demokracji w zarzadzaniu).

2021-04-21 22:19 UTC, ad-m requested changes
Chciałbym się odnieść, ale 148 zmienionych plików przekracza zakres percepcji indywidualnego PR-a. Zapewne brakuje rebase.

2021-04-26 20:28 UTC, fervero approved these changes

2021-05-05 23:17 UTC, MichalKarol commented
@ad-m @fervero PRka przeniesiona do #930 aby posprzątać pliki.

2021-05-05 23:17 UTC, closed without merging